In [1]:
import numpy as np
from numpy import mean
import pandas as pd


In [2]:
data=pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data')

In [3]:
data

5.1  3.5  1.4  0.2     Iris-setosa
0    4.9  3.0  1.4  0.2     Iris-setosa
1    4.7  3.2  1.3  0.2     Iris-setosa
2    4.6  3.1  1.5  0.2     Iris-setosa
3    5.0  3.6  1.4  0.2     Iris-setosa
4    5.4  3.9  1.7  0.4     Iris-setosa
5    4.6  3.4  1.4  0.3     Iris-setosa
6    5.0  3.4  1.5  0.2     Iris-setosa
7    4.4  2.9  1.4  0.2     Iris-setosa
8    4.9  3.1  1.5  0.1     Iris-setosa
9    5.4  3.7  1.5  0.2     Iris-setosa
10   4.8  3.4  1.6  0.2     Iris-setosa
11   4.8  3.0  1.4  0.1     Iris-setosa
12   4.3  3.0  1.1  0.1     Iris-setosa
13   5.8  4.0  1.2  0.2     Iris-setosa
14   5.7  4.4  1.5  0.4     Iris-setosa
15   5.4  3.9  1.3  0.4     Iris-setosa
16   5.1  3.5  1.4  0.3     Iris-setosa
17   5.7  3.8  1.7  0.3     Iris-setosa
18   5.1  3.8  1.5  0.3     Iris-setosa
19   5.4  3.4  1.7  0.2     Iris-setosa
20   5.1  3.7  1.5  0.4     Iris-setosa
21   4.6  3.6  1.0  0.2     Iris-setosa
22   5.1  3.3  1.7  0.5     Iris-setosa
23   4.8  3.4  1.9  0.2     Iris-setosa
24   5.0  3.0  1.6  0.2     Iris-setosa
25   5.0  3.4  1.6  0.4     Iris-setosa
26   5.2  3.5  1.5  0.2     Iris-setosa
27   5.2  3.4  1.4  0.2     Iris-setosa
28   4.7  3.2  1.6  0.2     Iris-setosa
29   4.8  3.1  1.6  0.2     Iris-setosa
..   ...  ...  ...  ...             ...
119  6.9  3.2  5.7  2.3  Iris-virginica
120  5.6  2.8  4.9  2.0  Iris-virginica
121  7.7  2.8  6.7  2.0  Iris-virginica
122  6.3  2.7  4.9  1.8  Iris-virginica
123  6.7  3.3  5.7  2.1  Iris-virginica
124  7.2  3.2  6.0  1.8  Iris-virginica
125  6.2  2.8  4.8  1.8  Iris-virginica
126  6.1  3.0  4.9  1.8  Iris-virginica
127  6.4  2.8  5.6  2.1  Iris-virginica
128  7.2  3.0  5.8  1.6  Iris-virginica
129  7.4  2.8  6.1  1.9  Iris-virginica
130  7.9  3.8  6.4  2.0  Iris-virginica
131  6.4  2.8  5.6  2.2  Iris-virginica
132  6.3  2.8  5.1  1.5  Iris-virginica
133  6.1  2.6  5.6  1.4  Iris-virginica
134  7.7  3.0  6.1  2.3  Iris-virginica
135  6.3  3.4  5.6  2.4  Iris-virginica
136  6.4  3.1  5.5  1.8  Iris-virginica
137  6.0  3.0  4.8  1.8  Iris-virginica
138  6.9  3.1  5.4  2.1  Iris-virginica
139  6.7  3.1  5.6  2.4  Iris-virginica
140  6.9  3.1  5.1  2.3  Iris-virginica
141  5.8  2.7  5.1  1.9  Iris-virginica
142  6.8  3.2  5.9  2.3  Iris-virginica
143  6.7  3.3  5.7  2.5  Iris-virginica
144  6.7  3.0  5.2  2.3  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica

[149 rows x 5 columns]

In [4]:
data.dtypes

5.1            float64
3.5            float64
1.4            float64
0.2            float64
Iris-setosa     object
dtype: object

In [5]:
data.shape

(149, 5)

In [6]:
data.columns

Index(['5.1', '3.5', '1.4', '0.2', 'Iris-setosa'], dtype='object')

In [22]:
data.columns=[i for i in 'abcd']+['class']
data.columns
#Species = ['Iris-setosa', 'Iris-versicolor', 'Iris-virginica']
data['class']=data['class'].replace('Iris-setosa',0)
data['class']=data['class'].replace('Iris-versicolor',1)
data['class']=data['class'].replace('Iris-virginica',1)
y=np.array(data['class'])

y
len(y)

149

In [23]:
data.head()
data1=data.drop('class',axis=1)
x=np.array(data1)
x
len(x)


149

In [24]:
theta=np.zeros(4)
theta

array([ 0.,  0.,  0.,  0.])

In [25]:
n=4
m=len(data['a'])#length
x=np.ones((m,n+1))
x[:,1]=data['a'].values
x[:,2]=data['b'].values
x[:,3]=data['c'].values
x[:,4]=data['d'].values

x_train=x[:int(len(x)*0.8)]
x_test=x[int(len(x)*0.8):]
y_train=y[:int(len(x)*0.8)]
y_test=y[int(len(x)*0.8):]
x_train,y_train,m

(array([[ 1. ,  4.9,  3. ,  1.4,  0.2],
        [ 1. ,  4.7,  3.2,  1.3,  0.2],
        [ 1. ,  4.6,  3.1,  1.5,  0.2],
        [ 1. ,  5. ,  3.6,  1.4,  0.2],
        [ 1. ,  5.4,  3.9,  1.7,  0.4],
        [ 1. ,  4.6,  3.4,  1.4,  0.3],
        [ 1. ,  5. ,  3.4,  1.5,  0.2],
        [ 1. ,  4.4,  2.9,  1.4,  0.2],
        [ 1. ,  4.9,  3.1,  1.5,  0.1],
        [ 1. ,  5.4,  3.7,  1.5,  0.2],
        [ 1. ,  4.8,  3.4,  1.6,  0.2],
        [ 1. ,  4.8,  3. ,  1.4,  0.1],
        [ 1. ,  4.3,  3. ,  1.1,  0.1],
        [ 1. ,  5.8,  4. ,  1.2,  0.2],
        [ 1. ,  5.7,  4.4,  1.5,  0.4],
        [ 1. ,  5.4,  3.9,  1.3,  0.4],
        [ 1. ,  5.1,  3.5,  1.4,  0.3],
        [ 1. ,  5.7,  3.8,  1.7,  0.3],
        [ 1. ,  5.1,  3.8,  1.5,  0.3],
        [ 1. ,  5.4,  3.4,  1.7,  0.2],
        [ 1. ,  5.1,  3.7,  1.5,  0.4],
        [ 1. ,  4.6,  3.6,  1. ,  0.2],
        [ 1. ,  5.1,  3.3,  1.7,  0.5],
        [ 1. ,  4.8,  3.4,  1.9,  0.2],
        [ 1. ,  5. ,  3. ,  1.6,  0.2],


In [26]:

def sigmoid(x,theta):#sigmoid fun
    z=np.matmul(x,theta)
    return 1/(1+np.exp(-z))

#def normalize(x):
#    min=np.min(x,axis=0)
#    max=np.max(x,axis=0)
#    rng=max-min
#   norm=1-((x-min)/rng)
#   return norm

def grad_descent(x,y,alpha,iteration):
    theta=(np.zeros(n+1))
    #b = np.zeros((m,1))

    for i in range(iteration):
        h=sigmoid(x,theta)
        gradient=(np.matmul(x.T,(h-y)))/m
        theta=theta-alpha*gradient
        loss=(-y*np.log(h)-(1-y)*np.log(1-h)).mean()
        
        if i%1000==0:
            print(loss)
    return theta


#def classify(x,theta):
#    prediction=sigmoid(x,theta)
#    if prediction>=0.5:
#       return 1
#   else: 
#       return 0
   


In [12]:
th=grad_descent(x_train,y_train,0.01,300000)
th

0.69314718056
0.077235188579
0.0412758543449
0.0284703733076
0.021863466789
0.0178151194021
0.0150724726235
0.0130874695485
0.0115819001885
0.0103993217376
0.00944491145017
0.00865779543329
0.00799707443441
0.00743423481275
0.00694877939538
0.00652558842142
0.0061532601225
0.00582303101387
0.0055280523929
0.00526289294615
0.00502318901598
0.00480539373872
0.00460659387283
0.0044243738992
0.00425671372945
0.00410191069683
0.0039585193517
0.00382530448784
0.00370120412235
0.00358530004896
0.00347679421409
0.00337498961324
0.0032792747283
0.00318911076184
0.00310402109796
0.00302358254883
0.00294741804301
0.00287519048543
0.00280659757534
0.00274136741199
0.00267925475156
0.00262003780522
0.00256351548914
0.00250950505342
0.00245784003056
0.00240836845394
0.00236095130594
0.00231546116166
0.00227178100001
0.00222980315869
0.00218942841291
0.0021505651611
0.00211312870353
0.00207704060139
0.0020422281063
0.0020086236512
0.00197616439512
0.00194479181522
0.00191445134054
0.00188509202242
0.

array([-0.58946672, -0.93964779, -3.31053032,  5.15429993,  2.39635747])

In [13]:
predicted_class=sigmoid(x_test,th)
predicted_class

array([ 0.99999997,  0.99999967,  1.        ,  0.99999926,  0.99999994,
        0.99999997,  0.99999844,  0.99999835,  0.99999999,  0.99999993,
        1.        ,  0.99999997,  0.99999999,  0.99999925,  0.99999997,
        1.        ,  0.99999995,  0.99999986,  0.99999749,  0.99999982,
        0.99999997,  0.99999948,  0.99999987,  0.99999999,  0.99999998,
        0.99999981,  0.99999982,  0.99999968,  0.99999984,  0.99999951])

In [14]:
pred=[]
for i in sigmoid(x,th):
    if i>=0.5:
        pred.append(1)
    else:
        pred.append(0)
np.array(pred)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [15]:
c=0
t=0
for i in pred:
    if pred[i]==y[i]:
        c+=1
    t+=1
c/t
    

1.0

In [28]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x,y,train_size=0.9)
#X_train, X_test, y_train, y_test
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_train, y_train)
y_predicted = model.predict(X_test)
model.predict_proba(X_test)
model.score(X_test,y_test)

C:\Users\ashish\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2026: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)


1.0

In [17]:
# Normalize the data attributes for the Iris dataset.
from sklearn.datasets import load_iris
from sklearn import preprocessing
# load the iris dataset
iris = load_iris()
#print(iris.data.shape)
# separate the data from the target attributes
X = iris.data
y = iris.target
# normalize the data attributes
normalized_X = preprocessing.normalize(X)
normalized_X

array([[ 0.80377277,  0.55160877,  0.22064351,  0.0315205 ],
       [ 0.82813287,  0.50702013,  0.23660939,  0.03380134],
       [ 0.80533308,  0.54831188,  0.2227517 ,  0.03426949],
       [ 0.80003025,  0.53915082,  0.26087943,  0.03478392],
       [ 0.790965  ,  0.5694948 ,  0.2214702 ,  0.0316386 ],
       [ 0.78417499,  0.5663486 ,  0.2468699 ,  0.05808704],
       [ 0.78010936,  0.57660257,  0.23742459,  0.0508767 ],
       [ 0.80218492,  0.54548574,  0.24065548,  0.0320874 ],
       [ 0.80642366,  0.5315065 ,  0.25658935,  0.03665562],
       [ 0.81803119,  0.51752994,  0.25041771,  0.01669451],
       [ 0.80373519,  0.55070744,  0.22325977,  0.02976797],
       [ 0.786991  ,  0.55745196,  0.26233033,  0.03279129],
       [ 0.82307218,  0.51442011,  0.24006272,  0.01714734],
       [ 0.8025126 ,  0.55989251,  0.20529392,  0.01866308],
       [ 0.81120865,  0.55945424,  0.16783627,  0.02797271],
       [ 0.77381111,  0.59732787,  0.2036345 ,  0.05430253],
       [ 0.79428944,  0.