# Basic PSO

In [6]:
import random
import numpy as np

bounds=[-10,10]# constraints i.e -10<=x<=10
x=random.sample(list(range(-10,10)),9)#initial positions Xi
v=np.zeros(len(x),dtype=int)#initial velocity Vi

def obj_function(x):  #objective function to maximize
    return -x**2+5*x+20

def evaluate(val):    #fitness function
    solutions=[]
    for roots in val:
        solutions.append(obj_function(roots))
    return solutions

def check_bounds(X,bounds):#function for bounds monitoring of x i.e -10<=x<=10
    for i in range(len(X)):
        if X[i]<bounds[0]:# if minimum is less than lower bounds 
            X[i]=bounds[0]# replace new minimum with minimum bounds
        elif X[i]>bounds[1]:#if maximum is more than upper bounds
            X[i]=bounds[1]# replace new maximum with upper bounds
    return X
            
def PSO(x,v,bounds,max_iter):#previous position, velocity and bounds as argument in PSO function
    
    w=0.5
    c1=1 #cognitive components
    c2=1 #social components
    new_V=np.zeros(len(v)) #updated velocity list
    new_X=np.zeros(len(x)) #updated position list
    fit_best=evaluate(x)
    Pbest=x
    iterations=1

    while iterations<=max_iter:
        #infinite loop until maxima is achived
        #x-previous position
        #v-previous velocity
        #nX-new position
        #nV-new velocity
        
        print("iteraton no.-{}\n".format(iterations))
        print("previous position.-{}".format(x))
       # print("pbest-{}".format(Pbest))
        r1=random.random()# random number in range 0-1 for robustness 
        r2=random.random()# random number in range 0-1 for robustness 
        for i in range(len(fit_best)):
            if fit_best[i]==max(fit_best):
                max_index=i#finding index value of Pbest (Xi) at which max best fit is achieved to select as gbest
        Gbest=Pbest[max_index]
       # print("gbest-{}, r1-{}, r2-{}".format(Gbest,r1,r2))
        for k in range(len(x)):
            new_V[k]=w*v[k]+c1*r1*(Pbest[k]-x[k])+c2*r2*(Gbest-x[k])# updating with new velocity
            new_X[k]=x[k]+new_V[k]                                    # updating with new position
        new_X=check_bounds(new_X,bounds)# bounds checking if necessary
        #print("updated velocity is-{}".format(V))
        
        new_fitness=evaluate(new_X)#evaluate on new position
    
        print("updated position is-{}".format(new_X))
        print("previous fit_best is -{}".format(fit_best))
        print("new_fitness is -{}\n".format(new_fitness))
        for f in range(len(new_fitness)):
            if new_fitness[f] >= fit_best[f]:
                Pbest[f]=new_X[f]#new position is considered as best positions  
        print("pbest-{}".format(Pbest))
        fit_best=new_fitness     #new_fitness is now considered previous fit_best for next iteration
        v=new_V                      # now new V has become previous v before new iteration
        x=new_X
        iterations+=1
       
    return new_fitness, x

fitness, position=PSO(x,v,bounds,20)
fitness, position

iteraton no.-1

previous position.-[4, 0, -1, -2, -10, -7, 7, -8, -9]
updated position is-[4.00000000e+00 2.85745591e+00 2.57181988e+00 2.28618386e+00
 1.09566763e-03 8.58003739e-01 4.85690807e+00 5.72367715e-01
 2.86731691e-01]
previous fit_best is -[24, 20, 14, 6, -130, -64, 6, -84, -106]
new_fitness is -[24.0, 26.12222527595354, 26.244841904650432, 26.204282657230728, 20.005477137675577, 23.553848278383242, 20.694984343810575, 22.534233774263953, 21.351443394028067]

pbest-[4.0, 2.857455905037894, 2.571819881297367, 2.286183857556841, 0.0010956676326276948, 0.8580037388542081, 4.8569080712215795, 0.5723677151136819, 0.2867316913731557]
iteraton no.-2

previous position.-[4.00000000e+00 2.85745591e+00 2.57181988e+00 2.28618386e+00
 1.09566763e-03 8.58003739e-01 4.85690807e+00 5.72367715e-01
 2.86731691e-01]
updated position is-[3.91241444 4.26866675 4.35772982 4.4467929  5.15929751 4.89210828
 3.64522521 4.98117136 5.07023444]
previous fit_best is -[24.0, 26.12222527595354, 26.244841

([26.24999328066702,
  26.249893600906773,
  26.24999100333378,
  26.249936194249305,
  26.24962111116347,
  26.249770140720866,
  26.24997778200236,
  26.249724580655094,
  26.249674904135965],
 array([2.49740783, 2.48968501, 2.50299944, 2.50798785, 2.51946507,
        2.51516111, 2.4952864 , 2.51659576, 2.51803041]))

# My own proposed PSO

In [60]:
import random
import numpy as np

bounds=[-10,10]# constraints i.e -10<=x<=10
x=random.sample(list(range(-10,10)),9)#initial positions Xi
v=np.zeros(len(x),dtype=int)#initial velocity Vi

def obj_function(x):  #objective function to maximize
    return -x**2+5*x+20

def evaluate(val):    #fitness function
    solutions=[]
    for roots in val:
        solutions.append(obj_function(roots))
    return solutions

def check_bounds(X,bounds):#function for bounds monitoring of x i.e -10<=x<=10
    for i in range(len(X)):
        if X[i]<bounds[0]:# if minimum is less than lower bounds 
            X[i]=random.uniform(-10,-1)# replace new minimum with minimum bounds, random number generation using mersenne twister
        elif X[i]>bounds[1]:#if maximum is more than upper bounds
            X[i]=random.uniform(0,10)# replace new maximum with upper bounds, random number generation using mersenne twister
    return X

def selection_mutation(x,K=None):#modified tournament selection (NEW proposed )
    t=0 #tournament iteration
    n=K # number of minimum value position to be selected from original x
    n_tournaments=K # max. no. of tournaments to be held
    solutions=[]
    fittest_x=[]
    min_idx=[]
    for roots in range(len(x)):
        solutions.append((obj_function(x[roots]),roots))
    solutions.sort(reverse=True)
    #print(solutions)
    for j in range(n):
        min_idx.append(solutions[-n:][j][1])
    while t < n_tournaments:
        x_list=random.choices(x,k=K)
        #print(x_list)
        sol=[]
        for i in range(len(x_list)):
            sol.append((obj_function(x_list[i]),x_list[i]))      
        fittest_x.append(max(sol)[1])
        t=t+1
    for k in range(len(fittest_x)):
        index=min_idx[k]
        x[index]=fittest_x[k]
    #print(min_idx)
    #print(fittest_x)
    return x               
                               
            
def PSO(x,v,bounds,max_iter,N=None):#previous position, velocity and bounds as argument in PSO function
    #N=number of tournaments
    #w=0.5
    c1=1 #cognitive components
    c2=1 #social components
    new_V=np.zeros(len(v)) #updated velocity list
    new_X=np.zeros(len(x)) #updated position list
    fit_best=evaluate(x)
    Pbest=x
    old_Gbest=0
    iterations=1
    while iterations<=max_iter:
        #infinite loop until maxima is achived
        #x-previous position
        #v-previous velocity
        #X-new position
        #V-new velocity
        print("iteraton no.-{}\n".format(iterations))
        print("previous position.-{}".format(x))
        r1=random.random()# random number in range 0-1 for robustness 
        r2=random.random()# random number in range 0-1 for robustness 
        
        for i in range(len(fit_best)):
            if fit_best[i]==max(fit_best):
                max_index=i#finding index value of Pbest (Xi) at which max best fit is achieved to select as gbest
        Gbest=Pbest[max_index]
        print("old_gbest-{}, r1-{}, r2-{}".format(old_Gbest,r1,r2))
        print("gbest-{}, r1-{}, r2-{}".format(Gbest,r1,r2))
        if Gbest<old_Gbest:
            c=random.uniform(1,2)
            c1=c2=c
            print('c1 and c2 are- ',c)
        for k in range(len(x)):
            if Pbest[k]!=0:# zero division handling
                w=(1.1-Gbest/Pbest[k])# GLbest weight initialisation
            else:
                w=0
            new_V[k]=w*v[k]+c1*r1*(Pbest[k]-x[k])+c2*r2*(Gbest-x[k])# updating with new velocity
            new_X[k]=x[k]+new_V[k]                                      # updating with new position
        new_X=check_bounds(new_X,bounds)# bounds checking if necessary
        #print("updated velocity is-{}".format(V))
        new_X=selection_mutation(new_X,K=N)
        new_fitness=evaluate(new_X)
        print("updated position is-{}".format(new_X))
        print("previous fit_best is -{}".format(fit_best))
        print("new_fitness is -{}".format(new_fitness))
        for fit in range(len(new_fitness)):
            if new_fitness[fit] > fit_best[fit]:
                Pbest[fit]=new_X[fit]#new position is considered as best positions
            #elif fit_best[fit] > new_fitness[fit]:
            #    Pbest[fit]=x[fit]#previous position is considered as best position
        print('Pbest - \n',Pbest)
        fit_best=new_fitness     #new_fitness is now considered previous fit_best for next iteration
        v=new_V                      # now new V has become previous v before new iteration
        x=new_X                      # now new X has become previous x before new iteration
        old_Gbest=Gbest          #Gbest of current iteration will be used old_Gbest in next iteration
        
        iterations+=1
    return new_fitness, x

fitness, position=PSO(x,v,bounds,20,N=4)#PSO with 10 iterations and 4 number of tournaments
fitness, position

iteraton no.-1

previous position.-[-6, 3, 4, -4, -10, 1, 7, 5, -8]
old_gbest-0, r1-0.2049975410150373, r2-0.8899478668255569
gbest-3, r1-0.2049975410150373, r2-0.8899478668255569
updated position is-[2.0095308  3.         3.11005213 2.22963507 2.22963507 2.77989573
 2.77989573 2.77989573 2.0095308 ]
previous fit_best is -[-46, 26, 24, -16, -130, 24, 6, 20, -84]
new_fitness is -[26.009439965254114, 26.0, 25.877836394809314, 26.17690280342508, 26.17690280342508, 26.171658378283905, 26.171658378283905, 26.171658378283905, 26.009439965254114]
Pbest - 
 [2.009530801430012, 3, 3.110052133174443, 2.229635067778899, 2.229635067778899, 2.779895733651114, 2.779895733651114, 2.779895733651114, 2.009530801430012]
iteraton no.-2

previous position.-[2.0095308  3.         3.11005213 2.22963507 2.22963507 2.77989573
 2.77989573 2.77989573 2.0095308 ]
old_gbest-3, r1-0.17415909725676215, r2-0.1521316541012313
gbest-2.229635067778899, r1-0.17415909725676215, r2-0.1521316541012313
c1 and c2 are-  1.781

([26.25, 26.25, 26.25, 26.25, 26.25, 26.25, 26.25, 26.25, 26.25],
 array([2.49999997, 2.49999998, 2.5       , 2.5       , 2.49999998,
        2.49999998, 2.5       , 2.49999996, 2.49999998]))

In [3]:
import random
import numpy as np

bounds=[-50,50]# constraints i.e -10<=x<=10
x=random.sample(list(range(-50,50)),100)#initial positions Xi
v=np.zeros(len(x),dtype=int)#initial velocity Vi

def obj_function(x,y):  #objective function to maximize
    return (-x**2-y**2)*np.exp(np.sin((1/(50*x**2))+(1/(50*y**2))))

def evaluate(val):    #fitness function
    solutions=[]
    x=np.array(val)
    y=x
    for i in x:
        for j in y:
        solutions.append(obj_function(i,j))
    return solutions

def check_bounds(X,bounds):#function for bounds monitoring of x i.e -10<=x<=10
    for i in range(len(X)):
        if X[i]<bounds[0]:# if minimum is less than lower bounds 
            X[i]=random.uniform(-50,-1)# replace new minimum with minimum bounds, random number generation using mersenne twister
        elif X[i]>bounds[1]:#if maximum is more than upper bounds
            X[i]=random.uniform(0,50)# replace new maximum with upper bounds, random number generation using mersenne twister
    return X

def selection_mutation(x,K=None):#modified tournament selection (NEW proposed )
    t=0 #tournament iteration
    n=K # number of minimum value position to be selected from original x
    n_tournaments=K # max. no. of tournaments to be held
    solutions=[]
    fittest_x=[]
    min_idx=[]
    for roots1 in range(len(x)):
        for roots2 in range(len(y))
        solutions.append((obj_function(x[roots1],y[roots2]),(roots))
    solutions.sort(reverse=True)
    #print(solutions)
    for j in range(n):
        min_idx.append(solutions[-n:][j][1])
    while t < n_tournaments:
        x_list=random.choices(x,k=K)
        #print(x_list)
        sol=[]
        for i in range(len(x_list)):
            sol.append((obj_function(x_list[i]),x_list[i]))      
        fittest_x.append(max(sol)[1])
        t=t+1
    for k in range(len(fittest_x)):
        index=min_idx[k]
        x[index]=fittest_x[k]
    #print(min_idx)
    #print(fittest_x)
    return x               
                               
            
def PSO(x,v,bounds,max_iter,N=None):#previous position, velocity and bounds as argument in PSO function
    #N=number of tournaments
    #w=0.5
    c1=1 #cognitive components
    c2=1 #social components
    new_V=np.zeros(len(v)) #updated velocity list
    new_X=np.zeros(len(x)) #updated position list
    fit_best=evaluate(x)
    Pbest=x
    old_Gbest=0
    iterations=1
    while iterations<=max_iter:
        #infinite loop until maxima is achived
        #x-previous position
        #v-previous velocity
        #X-new position
        #V-new velocity
        print("iteraton no.-{}\n".format(iterations))
        print("previous position.-{}".format(x))
        r1=random.random()# random number in range 0-1 for robustness 
        r2=random.random()# random number in range 0-1 for robustness 
        
        for i in range(len(fit_best)):
            if fit_best[i]==max(fit_best):
                max_index=i#finding index value of Pbest (Xi) at which max best fit is achieved to select as gbest
        Gbest=Pbest[max_index]
        print("old_gbest-{}, r1-{}, r2-{}".format(old_Gbest,r1,r2))
        print("gbest-{}, r1-{}, r2-{}".format(Gbest,r1,r2))
        if Gbest<old_Gbest:
            c=random.uniform(1,2)
            c1=c2=c
            print('c1 and c2 are- ',c)
        for k in range(len(x)):
            if Pbest[k]!=0:# zero division handling
                w=(1.1-Gbest/Pbest[k])# GLbest weight initialisation
            else:
                w=0
            new_V[k]=w*v[k]+c1*r1*(Pbest[k]-x[k])+c2*r2*(Gbest-x[k])# updating with new velocity
            new_X[k]=x[k]+new_V[k]                                      # updating with new position
        new_X=check_bounds(new_X,bounds)# bounds checking if necessary
        #print("updated velocity is-{}".format(V))
        new_X=selection_mutation(new_X,K=N)
        new_fitness=evaluate(new_X)
        print("updated position is-{}".format(new_X))
        print("previous fit_best is -{}".format(fit_best))
        print("new_fitness is -{}".format(new_fitness))
        for fit in range(len(new_fitness)):
            if new_fitness[fit] > fit_best[fit]:
                Pbest[fit]=new_X[fit]#new position is considered as best positions
            #elif fit_best[fit] > new_fitness[fit]:
            #    Pbest[fit]=x[fit]#previous position is considered as best position
        print('Pbest - \n',Pbest)
        fit_best=new_fitness     #new_fitness is now considered previous fit_best for next iteration
        v=new_V                      # now new V has become previous v before new iteration
        x=new_X                      # now new X has become previous x before new iteration
        old_Gbest=Gbest          #Gbest of current iteration will be used old_Gbest in next iteration
        
        iterations+=1
    return new_fitness, x

fitness, position=PSO(x,v,bounds,20,N=10)#PSO with 10 iterations and 4 number of tournaments
fitness, position

iteraton no.-1

previous position.-[30, -42, 6, -15, -49, -30, 13, 40, 3, 11, -17, 8, -45, -12, -47, 33, 36, 14, 15, -7, -2, -46, 22, 46, 27, -35, -28, -19, -5, -8, -38, 43, 5, 38, -1, -9, 20, 0, 49, -13, -40, -11, 26, 41, -50, -3, 24, 32, 34, 17, -21, 23, 12, 48, -41, -24, -31, 21, -37, -20, 37, -18, -27, 28, 39, 44, -29, 42, 9, -4, -25, -23, 7, 2, -48, 18, 16, 1, -32, -43, 45, 29, -33, -34, -26, -14, 25, -44, 31, -16, 10, 4, -6, 35, -22, 47, -36, -39, -10, 19]
old_gbest-0, r1-0.07240211964073406, r2-0.35120818316659996
gbest-1, r1-0.07240211964073406, r2-0.35120818316659996


C:\Users\Ashish\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: RuntimeWarning: divide by zero encountered in long_scalars
  if __name__ == '__main__':
C:\Users\Ashish\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: RuntimeWarning: divide by zero encountered in true_divide
  if __name__ == '__main__':
C:\Users\Ashish\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: RuntimeWarning: invalid value encountered in sin
  if __name__ == '__main__':
C:\Users\Ashish\Anaconda3\lib\site-packages\ipykernel_launcher.py:79: RuntimeWarning: invalid value encountered in greater


TypeError: obj_function() missing 1 required positional argument: 'y'

In [8]:
import random
import numpy as np

bounds=[-10,10]# constraints i.e -10<=x<=10
x=random.sample(list(range(-10,10)),9)#initial positions Xi
v=np.zeros(len(x),dtype=int)#initial velocity Vi

def obj_function(x):  #objective function to maximize
    return -x**2+(np.cos(x**2)+1/np.sin(x**2))+100

def evaluate(val):    #fitness function
    solutions=[]
    for roots in val:
        solutions.append(obj_function(roots))
    return solutions

def check_bounds(X,bounds):#function for bounds monitoring of x i.e -10<=x<=10
    for i in range(len(X)):
        if X[i]<bounds[0]:# if minimum is less than lower bounds 
            X[i]=bounds[0]# replace new minimum with minimum bounds
        elif X[i]>bounds[1]:#if maximum is more than upper bounds
            X[i]=bounds[1]# replace new maximum with upper bounds
    return X
            
def PSO(x,v,bounds,max_iter):#previous position, velocity and bounds as argument in PSO function
    
    w=0.5
    c1=1 #cognitive components
    c2=1 #social components
    new_V=np.zeros(len(v)) #updated velocity list
    new_X=np.zeros(len(x)) #updated position list
    fit_best=evaluate(x)
    Pbest=x
    iterations=1

    while iterations<=max_iter:
        #infinite loop until maxima is achived
        #x-previous position
        #v-previous velocity
        #nX-new position
        #nV-new velocity
        
        print("iteraton no.-{}\n".format(iterations))
        print("previous position.-{}".format(x))
       # print("pbest-{}".format(Pbest))
        r1=random.random()# random number in range 0-1 for robustness 
        r2=random.random()# random number in range 0-1 for robustness 
        for i in range(len(fit_best)):
            if fit_best[i]==max(fit_best):
                max_index=i#finding index value of Pbest (Xi) at which max best fit is achieved to select as gbest
        Gbest=Pbest[max_index]
       # print("gbest-{}, r1-{}, r2-{}".format(Gbest,r1,r2))
        for k in range(len(x)):
            new_V[k]=w*v[k]+c1*r1*(Pbest[k]-x[k])+c2*r2*(Gbest-x[k])# updating with new velocity
            new_X[k]=x[k]+new_V[k]                                    # updating with new position
        new_X=check_bounds(new_X,bounds)# bounds checking if necessary
        #print("updated velocity is-{}".format(V))
        
        new_fitness=evaluate(new_X)#evaluate on new position
    
        print("updated position is-{}".format(new_X))
        print("previous fit_best is -{}".format(fit_best))
        print("new_fitness is -{}\n".format(new_fitness))
        for f in range(len(new_fitness)):
            if new_fitness[f] >= fit_best[f]:
                Pbest[f]=new_X[f]#new position is considered as best positions  
        print("pbest-{}".format(Pbest))
        fit_best=new_fitness     #new_fitness is now considered previous fit_best for next iteration
        v=new_V                      # now new V has become previous v before new iteration
        x=new_X
        iterations+=1
       
    return new_fitness, x

fitness, position=PSO(x,v,bounds,25)
fitness, position

iteraton no.-1

previous position.-[9, -4, -8, 2, -10, -9, -7, 6, 0]
updated position is-[ 7.80741674 -3.46996299 -6.93992599  1.7349815  -8.67490749 -7.80741674
 -6.07243524  5.20494449  0.        ]
previous fit_best is -[18.189102143164902, 79.56895226009169, 37.47878298957432, 94.0250076703255, -1.112538659136419, 18.189102143164902, 50.25210266840046, 62.863747016314406, inf]
new_fitness is -[37.6951784676114, 86.83165822068925, 50.169624401713385, 103.62891888116118, 18.776877949276184, 37.6951784676114, 62.44251790665319, 73.61056018120323, inf]

pbest-[7.807416737573176, -3.469962994476967, -6.939925988953934, 1.7349814972384836, -8.674907486192417, -7.807416737573176, -6.072435240334693, 5.204944491715451, 0.0]
iteraton no.-2

previous position.-[ 7.80741674 -3.46996299 -6.93992599  1.7349815  -8.67490749 -7.80741674
 -6.07243524  5.20494449  0.        ]
updated position is-[ 6.68776391 -2.97233951 -5.94467903  1.48616976 -7.43084878 -6.68776391
 -5.20159415  4.45850927  0.    

C:\Users\Ashish\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: RuntimeWarning: divide by zero encountered in double_scalars
  if __name__ == '__main__':


([696800.772114476,
  3527143.596335355,
  881861.6490829528,
  14093508.523507714,
  564427.8154122178,
  696800.772114476,
  191074.74626752865,
  1567675.4872597328,
  inf],
 array([-0.00119806,  0.00053247,  0.00106494, -0.00026637,  0.00133117,
         0.00119806,  0.0022883 , -0.0007987 ,  0.        ]))

In [64]:
14861683611693698/100000000000000000000000000000000000000

1.4861683611693698e-22

In [65]:
0.00000000000000000000014861683611693698

1.4861683611693698e-22

In [11]:
import random

print(random.randint(0, 8))

3


In [18]:
nZ=[1,2,3,4]

In [19]:
nZ[2]=5
nZ

[1, 2, 5, 4]

In [28]:
random.choice(nZ)

2

In [29]:
len(nZ)

4

In [11]:
x=3
X=x+2
X

5

In [12]:
x

3

In [10]:
old_fit=[25.427461107043754, 26.0, 26.058191447461283, 26.242565299709604, 25.626382821157396, 26.249037745113363, 24.505712968147265, 26.228017437844283, 26.208600101633003]
new_fit=[16.061256727367443, 26.248512128189283, 21.776226159561542, 24.540466662759517, 17.707425738408478, 25.171977959835488, 22.551829496000543, 25.658538154916453, 23.764004263688538]
previous=[3.4069393 ,2.0, 2.93795953 ,2.58622471 ,3.28969436 ,2.46897977,1.17928541 ,2.35173482 ,2.70346965]
updated=[5.69198109 ,2.46142706 ,4.61512975 ,3.80749124 ,5.42276825 ,3.5382784, 0.57693721 ,3.26906557 ,4.07670407]
p=[0,0,0,0,0,0,0,0,0]
for i in range(len(old_fit)):
    if new_fit[i]>old_fit[i]:
        p[i]=updated[i]
    elif old_fit[i]>new_fit[i]:
        p[i]=previous[i]
p        

[3.4069393,
 2.46142706,
 2.93795953,
 2.58622471,
 3.28969436,
 2.46897977,
 1.17928541,
 2.35173482,
 2.70346965]

In [ ]:
def tournament_selection(x,K=None):#selection algorithm for selecting fittest value among all
    x_list=random.choices(x,k=K)
    sol=[]
    print(x_list)
    for i in range(len(x_list)):
        sol.append((obj_function(x_list[i]),x_list[i]))      
    print(sol)
    return max(sol)[1]

In [30]:
import random
import numpy as np
def obj_function(x):  #objective function to maximize
    return -x**2+5*x+20
def selection_mutation(x,K=None):
    t=0 #tournament iteration
    n=K # number of minimum value position to be selected from original x
    n_tournaments=K # max. no. of tournaments to be held
    solutions=[]
    fittest_x=[]
    min_idx=[]
    for roots in range(len(x)):
        solutions.append((obj_function(x[roots]),roots))
    solutions.sort(reverse=True)
    #print(solutions)
    for j in range(n):
        min_idx.append(solutions[-n:][j][1])
    while t < n_tournaments:
        x_list=random.choices(x,k=K)
        #print(x_list)
        sol=[]
        for i in range(len(x_list)):
            sol.append((obj_function(x_list[i]),x_list[i]))      
        fittest_x.append(max(sol)[1])
        t=t+1
    for k in range(len(fittest_x)):
        index=min_idx[k]
        x[index]=fittest_x[k]
    #print(min_idx)
    #print(fittest_x)
    return x               
                             

In [31]:
x=[1.7811918646731684, 1.912476745869267, 1.9343575594019504, 2.087523254130733, 1.7593110511404841, 2.0, 1.8468343052712175, 1.8687151188039008, 2.1531656947287825]
selection_mutation(x,K=4)

[(26.129705964687034, 8), (26.079862934117102, 3), (26.0, 5), (25.930048629394282, 2), (25.904816425855635, 1), (25.85147939877323, 7), (25.823374575229465, 6), (25.733314864587964, 0), (25.701379881037386, 4)]
[2.087523254130733, 1.9343575594019504, 1.7811918646731684, 2.1531656947287825]
[1.9343575594019504, 1.7811918646731684, 1.9343575594019504, 2.087523254130733]
[2.1531656947287825, 2.1531656947287825, 1.7811918646731684, 1.8687151188039008]
[1.7593110511404841, 1.7811918646731684, 1.8687151188039008, 1.9343575594019504]
[7, 6, 0, 4]
[2.1531656947287825, 2.087523254130733, 2.1531656947287825, 1.9343575594019504]


[2.1531656947287825,
 1.912476745869267,
 1.9343575594019504,
 2.087523254130733,
 1.9343575594019504,
 2.0,
 2.087523254130733,
 2.1531656947287825,
 2.1531656947287825]

In [128]:
[25.733314864587964, 25.904816425855635, 25.930048629394282, 26.079862934117102, 25.701379881037386, 26.0, 25.823374575229465, 25.85147939877323, 26.129705964687034]

[25.733314864587964,
 25.904816425855635,
 25.930048629394282,
 26.079862934117102,
 25.701379881037386,
 26.0,
 25.823374575229465,
 25.85147939877323,
 26.129705964687034]

In [1]:
x=[(26.079862934117102, 2.087523254130733), (25.701379881037386, 1.7593110511404841), (25.823374575229465, 1.8468343052712175), (25.85147939877323, 1.8687151188039008)]
x.sort(reverse=True)
x

[(26.079862934117102, 2.087523254130733),
 (25.85147939877323, 1.8687151188039008),
 (25.823374575229465, 1.8468343052712175),
 (25.701379881037386, 1.7593110511404841)]

In [3]:
x1=x[-2:][0][0]
x1

25.823374575229465

In [39]:
import random
random.choices(x,k=4)

[2.500006340327847, 2.4999931891905014, 2.499999764759174, 2.499978394160988]

In [35]:
from numpy.random import randint
randint(0,len(x),3)

array([0, 4, 8])

In [12]:
for i in range(len(x)):
    print(x[i])

2.4999767502688193
2.499999764759174
2.4999866136218287
2.4999849697296606
2.4999931891905014
2.500006340327847
2.499998120867006
2.5000030525435104
2.499978394160988


In [10]:
list(range(0,9,2))

[0, 2, 4, 6, 8]

In [30]:
import random
random.uniform(1,2)

1.8377424324007008

In [5]:
# Python3 program to implement the
# weighted K nearest neighbour algorithm.

import math

def weightedkNN(points,p,k=None):
    distance=[]
    for group in points:
        for feature in points[group]:

            #calculate the euclidean distance of p from training points
            euclidean_distance = math.sqrt((feature[0]-p[0])**2 +(feature[1]-p[1])**2)

            # Add a tuple of form (distance,group) in the distance list
            distance.append((euclidean_distance,group))

    # sort the distance list in ascending order
    # and select first k distances
    distance = sorted(distance)[:k]
    
    freq1 = 0 # weighted sum of group 0
    freq2 = 0 # weighted sum of group 1
    
    for d in distance:
        if d[1] == 0:
            freq1 += (1 / d[0])

        elif d[1] == 1:
            freq2 += (1 /d[0])

    print(freq1,freq2)
    print(distance)
    return 0 if freq1>freq2 else 1

# Driver function
def main():

    # Dictionary of training points having two keys - 0 and 1
    # key 0 have points belong to class 0
    # key 1 have points belong to class 1

    points = {0:[(0, 4),(1, 4.9),(1.6, 5.4),(2.2, 6),(2.8, 7),(3.2, 8),(3.4, 9)],
             1:[(1.8, 1),(2.2, 3),(3, 4),(4, 4.5),(5, 5),(6, 5.5)]}

    # query point p(x,y)
    p = (2, 4)

    # Number of neighbours
    k = 5

    print("The value classified to query point is: {}".format(weightedkNN(points,p,k)))

if __name__ == '__main__':
	main()


1.9300969659906113 1.9805806756909201
[(1.0, 1), (1.019803902718557, 1), (1.3453624047073711, 0), (1.456021977856104, 0), (2.0, 0)]
The value classified to query point is: 1


In [16]:
-0

0

In [107]:
a=[1,2,3,4,33,5,6,7,8,9]
for i in range(len(a)):
    for j in range(len(a)):
        if a[i]>a[j]:
            best=a[i]
best

9

In [137]:
a=[1,2,3,4,33,5,6,7,8,9]
a[3]=3.444
a

[1, 2, 3, 3.444, 33, 5, 6, 7, 8, 9]

In [ ]:
 #converge_fitness=np.zeros(len(v))
        #tolerance=0.001
        #for k in range(len(fit_best)):
        #    if k==len(fit_best)-1:
        #        if abs(fit_best[k]-fit_best[k-(len(fit_best)-1)])<=tolerance:
        #            converge_fitness[k]=fit_best[k]       
        #    elif abs(fit_best[k]-fit_best[k+1])<=tolerance:
        #            converge_fitness[k]=fit_best[k]
       # print("fitness values-{} \n".format(converge_fitness))

In [50]:
c=[4,5,6,7]
a=[1,2,3,4]
for i in range(len(a)):
    a[i]=c[i]
a

[4, 5, 6, 7]

In [52]:
V=np.zeros(len(v),dtype=int)
V

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [2]:
a=[1,2,3,4]
max(a)

4

In [7]:
abs(26.233)

26.233

In [4]:
def compare_float(x,y):
    tolerance=0.001
    if abs(x-y)<=tolerance:
        print("equivalent")
        print( abs(x-y))
    else:
        print("not equivalent")
        print( abs(x-y))
compare_float(26.24999999945945,26.249999999999943)

equivalent
5.404920955243142e-10


In [29]:
def compare_float(x,y):
    tolerance=0.01
    if abs(x-y)<=tolerance:
        return True

z=compare_float(2.3495,2.3345)
z

In [7]:
x = 13.949999999999999999
g = float("{:.2f}".format(x))

In [8]:
g

13.95

In [31]:
random.uniform(-10,-1)

-4.3318674891248214

In [5]:
a=np.zeros(len(x))
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
z=a
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
r1,r2=random.sample(,2)
r1,r2

(1, 0)

In [3]:
a=[10,20,0,33,66,89]
max(a)

89

In [1]:
import random
x=random.sample(list(range(-12,12)),9)#initial positions Xi
x

[-10, 8, 9, 6, 10, -1, 11, -5, 3]

In [26]:
random.randint(-10,-1)

-10

In [15]:
best=x
best

[4, -1, -2, 7, -5, 9, 2, -10, -6]

In [1]:
a=[1,2,3,4,5,6,7,8]
for x in a:
    if x==5:
        continue#skipping the iteration
    print(x)

1
2
3
4
6
7
8


In [2]:
a=[1,2,3,4,5,6,7,8]
for x in a:
    if x==5:
        break#break or stop the iteration
    print(x)

1
2
3
4


In [3]:
#include <iostream>
#include <cmath>
using namespace std;
bool compare_float(float x, float y, float epsilon = 0.01f){
   if(fabs(x - y) < epsilon)
      return true; //they are same
      return false; //they are not same
}
int main() {
   float x, y;
   x = 22.0f/7.0f;
   y = 3.1415f;
   if(compare_float(x, y)){
      cout << "They are equivalent" << endl;
      cout<<"absolute value "<<fabs(x-y)<<endl;
   } else {
      cout << "They are not equivalent" << endl;
   }
   if(compare_float(x, y, 0.001f)){
   cout << "They are equivalent" << endl;
   } else {
      cout << "They are not equivalent" << endl;
      cout<<"absolute value "<<fabs(x-y)<<endl;
   }
}

SyntaxError: invalid syntax (<ipython-input-3-df5c997d679c>, line 3)

# pattern

In [16]:
for i in range(5):#iteration over row 
    for j in range(5):#iteration over column
        print('*',end="")
    print('')
        

*****
*****
*****
*****
*****


In [37]:
n_range=int(input("enter the range for pattern -"))
for i in range(n_range):#i=0,iteration-1 <n
    for j in range(i+1):
        print('@',end='')
    print('')

enter the range for pattern -10
@
@@
@@@
@@@@
@@@@@
@@@@@@
@@@@@@@
@@@@@@@@
@@@@@@@@@
@@@@@@@@@@


In [30]:
list(range(1))

[0]

In [52]:
n=5
k = 2*n - 2
for i in range(0, n):
        for j in range(0, k):
            print(end=" ")
        k = k - 2
        for j in range(0, i+1):
            print("* ", end="")
        print("\r")

        * 
      * * 
    * * * 
  * * * * 
* * * * * 


In [40]:
rows = 5
for i in range(1, rows + 1):
    for j in range(1, i + 1):
        print(j, end=' ')
    print('')

1 
1 2 
1 2 3 
1 2 3 4 
1 2 3 4 5 


In [54]:
for i in range(10, 0, -2):
    print(i)

10
8
6
4
2


In [57]:
rows = 5
num = rows
for i in range(rows, 0, -1):
    for j in range(0, i):
        print(' ', end=' ')
    print("x")

          x
        x
      x
    x
  x


In [ ]:
*****
*****
*****
*****
*****

*
**
***
****
*****
******

     *
    **
   ***
  ****
******

10000
01000
00100
00010
00001
*
**
***
****
*****
****
***
**
*
a
ab
abc
abcd
abcde

In [4]:
import numpy as np
a=np.array([2,3,4,5,6,7,8,9])
b=a.T
a,b

(array([2, 3, 4, 5, 6, 7, 8, 9]), array([2, 3, 4, 5, 6, 7, 8, 9]))

In [8]:
for i,j in zip(range(len(a)),range(len(b))):
    print(a[i],j)

2 0
3 1
4 2
5 3
6 4
7 5
8 6
9 7
